# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4d04445a027ec1a9c87093458c6b341"
name = "test-bundle-app"
handle = "test-bundle-app"
application_url = "https://hungary-instantly-rt-standing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "emre-development-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hungary-instantly-rt-standing.trycloudflare.com/auth/callback",
  "https://hungary-instantly-rt-standing.trycloudflare.com/auth/shopify/callback",
  "https://hungary-instantly-rt-standing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://seller-inquiries-parade-combined.trycloudflare.com/webhooks"

[pos]
embedded = false
